name = "zonesteward"
compatibility_date = "2026-09-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "zonesteward-globe"
database_id = "d34b8df3-44a7-4a0e-8b80-90e06743e3a2"
